"""Add pgroonga index to pages content

Revision ID: cf3e2145e952
Revises: ce692f44ad60
Create Date: 2024-08-31 04:19:13.892238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf3e2145e952'
down_revision: Union[str, None] = 'ce692f44ad60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_pages_content_pgroonga', 'pages', ['content'], unique=False, postgresql_using='pgroonga')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pages_content_pgroonga', table_name='pages', postgresql_using='pgroonga')
    # ### end Alembic commands ###
