services:
  web:
    build:
      context: .
      dockerfile: dockerfiles/web/Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: dockerfiles/db/Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    ports:
      - 5432:5432

  nlm-ingestor:
    image: ghcr.io/nlmatics/nlm-ingestor:latest
    ports:
      - 5010:5001

volumes:
  postgres_data:
